spring:
  application:
    name: erstantrag-address-mcp-server
  main:
    banner-mode: off
  ai:
    mcp:
      server:
        name: erstantrag-address-mcp-server
        version: 0.0.1
  threads:
    virtual:
      enabled: true
logging:
  file:
    name: ./erstantrag-address-mcp-server.log
server:
  port: 8082